package com.minimumApp.minimumPad.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "notes")
public class Note {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "content")
    private String content;

    // Novo campo para armazenar timestamp da criação (epoch millis)
    // TODO: revisar se está funcionando como esperado
    @DynamoDBAttribute(attributeName = "createdAt")
    private Long createdAt;
}
