name: Deploy simples para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Debug Deploy EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar conteúdo do repositório
        run: |
          echo "Arquivos no repositório:"
          ls -R .

      - name: Configurar chave SSH
        run: |
          echo "Configurando chave SSH..."
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Testar conexão com EC2
        run: |
          echo "Testando conexão SSH com o servidor EC2..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo ✅ Conectado com sucesso ao EC2"

      - name: Fazer deploy completo via rsync (sem preservar atributos)
        run: |
          echo "Enviando arquivos via rsync..."
          rsync -az --no-times --no-perms --no-owner --no-group \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_TARGET_PATH }}/

      - name: Verificar arquivos no servidor remoto
        run: |
          echo "Listando arquivos no servidor remoto:"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "ls -lah ${{ secrets.EC2_TARGET_PATH }}"
