name: Deploy frontend para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Copiar frontend para EC2 se houver alterações
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Verificar se houve alterações no diretório frontend/
        id: check_changes
        run: |
          CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^frontend/')
          echo "Arquivos alterados no frontend:"
          echo "$CHANGED"
          if [ -n "$CHANGED" ]; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
            echo "$CHANGED" > changed_files.txt
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fazer backup do frontend no servidor
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
            mkdir -p /home/ec2-user/minimumpad/backups && \
            zip -r /home/ec2-user/minimumpad/backups/frontend_backup_$TIMESTAMP.zip /home/ec2-user/minimumpad/frontend \
          "

      - name: Copiar arquivos alterados do frontend para o servidor
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          while read file; do
            echo "Copiando $file..."
            rsync -avz --rsync-path="mkdir -p /home/ec2-user/minimumpad/frontend/$(dirname ${file#frontend/}) && rsync" \
              "$file" \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/minimumpad/frontend/"${file#frontend/}"
          done < changed_files.txt
