name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # necessário para comparar os 2 últimos commits

      - name: Verificar se houve alterações no diretório frontend/
        id: check-frontend
        run: |
          PREV_COMMIT=$(git rev-parse HEAD^)
          LAST_COMMIT=$(git rev-parse HEAD)
          
          echo "Analisando alterações entre $PREV_COMMIT e $LAST_COMMIT"

          CHANGED=$(git diff --name-only $PREV_COMMIT $LAST_COMMIT | grep '^frontend/' || true)

          echo "Arquivos modificados:"
          echo "$CHANGED"

          if [ -n "$CHANGED" ]; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
            echo "$CHANGED" > changed_files.txt
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Criar ZIP do frontend (caso tenha alterações)
        if: steps.check-frontend.outputs.changes == 'true'
        run: |
          zip -r frontend.zip frontend/

      - name: Copiar arquivos via SCP para o servidor
        if: steps.check-frontend.outputs.changes == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "frontend.zip"
          target: "~/"
