name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar arquivo de chave SSH
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Fazer backup da pasta frontend no servidor
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          ssh -i key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'mkdir -p /home/ec2-user/minimumpad/backups && cp -r /home/ec2-user/minimumpad/frontend /home/ec2-user/minimumpad/backups/frontend_'"$TIMESTAMP"
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}

      - name: Copiar arquivos modificados para o servidor (mantendo estrutura e removendo arquivos deletados)
        run: |
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" frontend/ $SSH_USER@$SSH_HOST:/home/ec2-user/minimumpad/frontend/
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
